overrides:
  ceph:
    log-whitelist:
      - \(OBJECT_MISPLACED\)
    conf:
      osd:
        osd op queue: debug_random
        osd op queue cut off: debug_random
        osd debug verify missing on start: true
        osd debug verify cached snaps: true
        osd load balancer op priority mode: recovery_op_prioritized
